remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Jeremy Howard
description: Some basic examples of client interfaces to a computer vision API

author:
  name: Jeremy Howard
